### ISSUE TITLE
Do not share universal EPPN, but only scoped identifier in EPPN 

### ISSUE THREAD

**Issue by Tyskai** [OpenConext/OpenConext-myconext#648]
institutions sometimes wrongly use (universal) EPPN. Send the eduID identifier in the uid and eppn attributes.

## Tasks
- [x] Create a feature toggle  `use_global_uid` in the `application.yaml` with default **true**
- [x] Add an array of entityID's in the `application.yaml` that contains a list of institutions that are **excluded** from the feature. These institutions cannot support scoped identifiers in EPPN.
- [x] Send the targetted eduID (`urn:mace:eduid.nl:1.1`)in SAML response instead of global_uid (in `urn:oasis:names:tc:SAML:attribute:subject-id`, `urn:mace:dir:attribute-def:uid` and `urn:mace:dir:attribute-def:eduPersonPrincipalName`).

## Current situation
```
urn:oasis:names:tc:SAML:attribute:subject-id	08e4c5a7-7ff9-44e0-8196-d8e0ff8f5d8d@eduid.nl
urn:mace:dir:attribute-def:cn	Mustafa Doe
urn:mace:terena.org:attribute-def:schacHomeOrganization	eduid.nl
urn:mace:dir:attribute-def:uid	08e4c5a7-7ff9-44e0-8196-d8e0ff8f5d8d
urn:mace:dir:attribute-def:eduPersonScopedAffiliation	student@example.com
urn:mace:dir:attribute-def:eduPersonScopedAffiliation	affiliate@eduid.nl
urn:mace:eduid.nl:1.1	5ea8de54-2c51-4516-8277-880d7ecc07e5
urn:mace:dir:attribute-def:sn	Doe
urn:mace:dir:attribute-def:mail	mustafa.cakir+2@surf.nl
urn:mace:dir:attribute-def:givenName	Bjkafnasjkldas
urn:mace:dir:attribute-def:eduPersonPrincipalName	08e4c5a7-7ff9-44e0-8196-d8e0ff8f5d8d@eduid.nl
```

The attributes that need the targeted eduID instead of the EPPN are;
```
urn:mace:dir:attribute-def:uid
urn:mace:dir:attribute-def:eduPersonPrincipalName
```

## Fixed situation
```
urn:oasis:names:tc:SAML:attribute:subject-id	5ea8de54-2c51-4516-8277-880d7ecc07e5@eduid.nl
urn:mace:dir:attribute-def:cn	Mustafa Doe
urn:mace:terena.org:attribute-def:schacHomeOrganization	eduid.nl
urn:mace:dir:attribute-def:uid	5ea8de54-2c51-4516-8277-880d7ecc07e5
urn:mace:dir:attribute-def:eduPersonScopedAffiliation	student@example.com
urn:mace:dir:attribute-def:eduPersonScopedAffiliation	affiliate@eduid.nl
urn:mace:eduid.nl:1.1	5ea8de54-2c51-4516-8277-880d7ecc07e5
urn:mace:dir:attribute-def:sn	Doe
urn:mace:dir:attribute-def:mail	mustafa.cakir+2@surf.nl
urn:mace:dir:attribute-def:givenName	Bjkafnasjkldas
urn:mace:dir:attribute-def:eduPersonPrincipalName	5ea8de54-2c51-4516-8277-880d7ecc07e5@eduid.nl
```

Todo:
- [x] Add `use_global_uid` to deploy project
- [x] Add `use_global_uid_ignored_entities` to deploy project

**Comment by phavekes** [comment]
@ricardovdheijden 
De bedoeling was:

```
if (use_global_uid==false && current_sp not in feature_force_global_uid_entities) then 
  uid-attribute = eduid-value
  eppn-attribute = eduid-value from EduID + @ + schachome-from-config
else
  uid-attribute = uid-value-from-database
  eppn-attribute = uid-value-from-database + @ + schacHomeOrganization-from-database
```

Dus er hoeft niets geschreven te worden in de database, we veranderen alleen de attributen in de response.
